name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run XOR subset scan
        run: python -m thermolab.experiments.xor.subset_scan --repeats 1 --max_subset 2

      - name: Run XOR THRML lab
        run: python -m thermolab.experiments.xor.thrml --repeats 4 --steps 10 --benchmark-samples 1000 --weight-threshold 0.1

      - name: Run Iris experiment
        run: python -m thermolab.experiments.iris --classes 0,1 --positive-class 0 --steps 10 --benchmark-samples 1000 --max-subset 2

      - name: Run Breast Cancer experiment
        run: python -m thermolab.experiments.breast_cancer --steps 10 --benchmark-samples 5000 --top-features 3 --max-subset 1
